#!/usr/bin/env bash
gnostr-set-relays 2>/tmp/gnostr-proxy.log || echo
(echo `pwd`) & clear && \
# gnostr-proxy sub-shell process
#
#
NVM_VERSION=v16.20.2
echo $NVM_VERSION > .nvmrc

export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] >/dev/null && \. "$NVM_DIR/nvm.sh" >/dev/null && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" && echo "gnostr-proxy:nvm:node -v $NVM_VERSION" && nvm install $NVM_VERSION >/tmp/gnostr-proxy.log 2>&1 && nvm use --silent 2>/tmp/gnostr-proxy.log \

(\

mkdir -p .gnostr >/tmp/gnostr-proxy.log;\
[ ! -d .gnostr/proxy ] && echo "gnostr-proxy:git:installing .gnostr/proxy"
[ ! -d .gnostr/proxy ] && git clone --depth 1 --branch master https://github.com/gnostr-org/gnostr-proxy.git .gnostr/proxy >/tmp/gnostr-proxy.log 2>&1; \
[   -d .gnostr/proxy ] && echo "gnostr-proxy:git:updating .gnostr/proxy"
[   -d .gnostr/proxy ] && cd .gnostr/proxy && git reset --hard 2>/tmp/gnostr-proxy.log && git pull -f origin master 2>/tmp/gnostr-proxy.log && echo ".gnostr/proxy" >> .gitignore >/tmp/gnostr-proxy.log 2>&1 &&  make run -k > /tmp/gnostr-proxy.log 2>&1;\
)#2>/tmp/gnostr-proxy.log;

