name: push.yml

on:
  push:
    branches: [ 'master', '**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  docker-start:

    strategy:
      matrix:
        version: [ 'latest' ]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
    - name: printenv
      run: printenv

    - uses: actions/checkout@v3
      with:
        fetch-depth: '0' ## all branches/tags
        submodules: 'recursive'
        set-safe-directory: 'true'

    - name: Run Apt-get update
      run: apt-get update

    - name: Install dependencies
      run: |
        apt-get --fix-missing -y install docker*
        apt-get --fix-missing -y install make git
        apt-get --fix-missing -y install quilt qemu-user-static debootstrap wget
        apt-get --fix-missing -y install bsdtar || echo
        apt-get --fix-missing -y install libarchive-tools || echo
        apt-get --fix-missing -y install python3 python3-pip || echo
        apt-get --fix-missing -y install util-linux coreutils || echo

    - name: Install act
      run: |
        wget -qO act.tar.gz https://github.com/nektos/act/releases/latest/download/act_Linux_x86_64.tar.gz && \
        tar xf act.tar.gz -C /usr/local/bin act && \
        act --version && rm -rf act.tar.gz

    - name: make docker-start
      run: make docker-start || echo

    - name: Nuke current Docker installation
      if: ${{ !env.ACT }}
      run: |
        systemctl stop docker
        apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
        rm -rf /var/lib/docker

    - name: Re-install Docker
      if: ${{ !env.ACT }}
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        docker --version

    - name: Enable experimental features in Docker
      if: ${{ !env.ACT }}
      run: |
        rm -rf /etc/docker/daemon.json
        echo '{"experimental": true}' | tee -a /etc/docker/daemon.json
        systemctl restart docker

    - name: make docker-start
      run: |
        echo "-P ubuntu-16.04=node:16-buster-slim" > $HOME/.actrc
        make docker-start || echo

    - name: node-app-template
      run: |
        git clone https://github.com/randymcmillan/node-app-template.git || echo && \
        type -P act && act -C node-app-template || echo "act not installed?"

