name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      matrix:
        version: [20.04, 22.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'
          
      - run: sudo apt-get update && sudo apt-get install nodejs -y
      - run: make docker-start

